// <auto-generated />
using System;
using BoxerTrucks.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoxerTrucks.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128194545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BoxerTrucks.Api.Models.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedHigh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedLow")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasHeavyItem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HelperCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LongCarry")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Miles")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StairFlights")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
