// <auto-generated />
using System;
using BoxerTrucks.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoxerTrucks.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129160032_Phase2_JobsDriversAssignments")]
    partial class Phase2_JobsDriversAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BoxerTrucks.Api.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("BoxerTrucks.Api.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustomerTotalHigh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustomerTotalLow")
                        .HasColumnType("TEXT");

                    b.Property<string>("DropoffAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlatformFeeHigh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlatformFeeLow")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledStartAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("BoxerTrucks.Api.Models.JobAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursHigh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursLow")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MilesPay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MilesRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PayHigh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PayLow")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "DriverId", "Role");

                    b.ToTable("JobAssignments");
                });

            modelBuilder.Entity("BoxerTrucks.Api.Models.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedHigh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedLow")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasHeavyItem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HelperCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LongCarry")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Miles")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StairFlights")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
